name: Update Blogger Post

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  update-blog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install node-fetch v2
        run: npm install node-fetch@2
        working-directory: website  # ✅ Use this instead

      - name: Run update script
        run: node update-blog.js
        working-directory: website  # ✅ This tells it where the script is

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add index.html
          git commit -m "🔄 Update latest Blogger post" || echo "No changes to commit"
          git push
        working-directory: website  # ✅ This tells Git to work inside /website
